"""Admin authorization and moderation against the disposable database only."""
def run(Client, sql, check, password):
    admin=Client(); admin.request('login.php')
    check('Community dashboard' in admin.request('login.php',dict(email='admin@mini.com',password=password))[1], 'admin login opens dashboard')
    member=Client(); member.register('moderation_member')
    uid=sql("SELECT id FROM users WHERE username='moderation_member'")
    check(member.request('admin.php')[0]==403,'member cannot open admin dashboard')
    check(member.request('admin.php',dict(action='suspend',id=uid))[0]==403,'member cannot call admin actions')
    check(admin.request('admin.php',dict(action='suspend',id=uid),token=False)[0]==403,'admin mutation requires CSRF')
    check(Client().request('setup_admin.php')[0]==404,'setup cannot run over HTTP')
    member.request('add_post.php',dict(content='Moderation original'))
    check('Moderation original' in admin.request('index.php')[1], 'all feed includes community posts')
    check('Moderation original' not in admin.request('index.php?feed=friends')[1], 'friends feed excludes unrelated accounts')
    pid=sql('SELECT MAX(id) FROM posts WHERE user_id='+uid)
    member.request('comment_post.php?post_id='+pid,dict(post_id=pid,comment='Moderation comment'))
    cid=sql('SELECT MAX(id) FROM comments WHERE user_id='+uid)
    check('Changes saved' in admin.request('admin.php?tab=posts',dict(action='save_post',id=pid,content='Moderated content'))[1],'admin edits posts')
    check(sql('SELECT content FROM posts WHERE id='+pid)=='Moderated content','post edit persisted')
    admin.request('admin.php?tab=comments',dict(action='save_comment',id=cid,content='Reviewed comment'))
    check(sql('SELECT comment FROM comments WHERE id='+cid)=='Reviewed comment','admin edits comments')
    check('Administrator' in admin.request('admin.php?tab=users&q=admin')[1],'admin account search')
    admin.request('admin.php?tab=users',dict(action='suspend',id=uid))
    check(sql('SELECT is_suspended FROM users WHERE id='+uid)=='1','admin suspends account')
    check(member.request('like_post.php',dict(post_id=pid))[0]==401,'suspension revokes existing session')
    member.request('login.php')
    check('Invalid email or password' in member.request('login.php',dict(email='moderation_member@example.test',password='Test-password-123'))[1],'suspended login blocked')
    admin.request('admin.php?tab=users',dict(action='restore',id=uid))
    member.request('login.php',dict(email='moderation_member@example.test',password='Test-password-123'))
    check('Your daily catch-up' in member.request('index.php')[1],'restored member can sign in')
    admin.request('admin.php?tab=users',dict(action='save_user',id=uid,username='moderation_member',email='moderation_member@example.test',bio='Reviewed bio',password='Replacement-password-123'))
    check(member.request('like_post.php',dict(post_id=pid))[0]==401,'password reset revokes sessions')
    member.request('login.php')
    check('Your daily catch-up' in member.request('login.php',dict(email='moderation_member@example.test',password='Replacement-password-123'))[1],'reset password works')
    aid=sql("SELECT id FROM users WHERE email='admin@mini.com'")
    check('protected' in admin.request('admin.php?tab=users',dict(action='delete_user',id=aid))[1],'administrator cannot delete own account')
    check(admin.request('delete_account.php',dict(delete_account='1'))[0]==403,'administrator self-delete endpoint protected')
    for tab in ['overview','users','posts','comments','messages','audit']:
        check(admin.request('admin.php?tab='+tab)[0]==200,'admin section '+tab)
    sql("INSERT INTO messages (sender_id,receiver_id,message) VALUES ("+uid+","+aid+",'Review message')")
    mid=sql('SELECT MAX(id) FROM messages')
    admin.request('admin.php?tab=messages',dict(action='delete_message',id=mid))
    check(sql('SELECT COUNT(*) FROM messages WHERE id='+mid)=='0','admin removes message')
    admin.request('admin.php?tab=comments',dict(action='delete_comment',id=cid))
    check(sql('SELECT COUNT(*) FROM comments WHERE id='+cid)=='0','admin removes comment')
    member.request('like_post.php',dict(post_id=pid))
    admin.request('admin.php?tab=posts',dict(action='delete_post',id=pid))
    check(sql('SELECT COUNT(*) FROM likes WHERE post_id='+pid)=='0','moderated post cleans up likes')
    member.request('add_post.php',dict(content='Delete with account'))
    admin.request('admin.php?tab=users',dict(action='delete_user',id=uid))
    check(sql('SELECT COUNT(*) FROM users WHERE id='+uid)=='0','admin deletes account')
    check(sql('SELECT COUNT(*) FROM posts WHERE user_id='+uid)=='0','account deletion removes posts')
    check(int(sql('SELECT COUNT(*) FROM admin_audit'))>=9,'moderation actions recorded in audit log')
    check('Reviewed bio' not in admin.request('admin.php?tab=audit')[1],'audit omits private content and passwords')
