"""Staff permissions and notification delivery in the disposable test database."""
import json
from urllib.parse import urlencode

def run(Client, sql, check, password):
    root=Client(); root.request('login.php'); root.request('login.php',dict(email='admin@mini.com',password=password))
    aid=sql("SELECT id FROM users WHERE email='admin@mini.com'")
    def staff_action(fields):
        fields=dict(fields,csrf_token=root.token)
        return root.request('admin.php?tab=team',raw=urlencode(fields,doseq=True).encode(),content_type='application/x-www-form-urlencoded')
    owner=Client(); owner.register('notice_owner')
    actor=Client(); actor.register('notice_actor')
    uid=sql("SELECT id FROM users WHERE username='notice_owner'")
    vid=sql("SELECT id FROM users WHERE username='notice_actor'")
    for route in ['add_post.php','friend_list.php','chat.php','profile.php','edit_profile.php']:
        check(root.request(route)[0]==403,'management cannot access social route '+route)
    check(root.request('add_post.php',dict(content='Forbidden staff post'))[0]==403,'management cannot publish by direct POST')
    html=root.request('admin.php')[1]
    check('Create a post' not in html and 'Home feed' not in html and '>Friends<' not in html,'management shell excludes social navigation')
    check(actor.request('send_request.php',dict(user_id=aid))[0]==404,'members cannot add staff as friends')
    check(actor.request('profile.php?user_id='+aid)[0]==404,'staff profiles not public')
    actor.request('send_request.php',dict(user_id=uid))
    actor.request('send_request.php',dict(user_id=uid))
    check(sql("SELECT COUNT(*) FROM notifications WHERE user_id="+uid+" AND kind='friend_request'")=='1','duplicate friend requests do not duplicate notifications')
    owner.request('accept_request.php',dict(user_id=vid)); owner.request('accept_request.php',dict(user_id=vid))
    check(sql("SELECT COUNT(*) FROM notifications WHERE user_id="+vid+" AND kind='friend_accepted'")=='1','accepted friend notification delivered once')
    owner.request('add_post.php',dict(content='Notification coverage post'))
    pid=sql('SELECT MAX(id) FROM posts WHERE user_id='+uid)
    check(sql("SELECT COUNT(*) FROM notifications WHERE user_id="+vid+" AND kind='friend_post'")=='1','friends receive new post notifications')
    actor.request('like_post.php',dict(post_id=pid)); actor.request('like_post.php',dict(post_id=pid)); actor.request('like_post.php',dict(post_id=pid))
    check(sql("SELECT COUNT(*) FROM notifications WHERE user_id="+uid+" AND kind='like'")=='1','repeated likes deduplicated')
    actor.request('comment_post.php?post_id='+pid,dict(comment='Comment notification'))
    check(sql("SELECT COUNT(*) FROM notifications WHERE user_id="+uid+" AND kind='comment'")=='1','post owner notified of comment')
    owner.request('comment_post.php?post_id='+pid,dict(comment='Self comment'))
    check(sql("SELECT COUNT(*) FROM notifications WHERE user_id="+uid+" AND kind='comment'")=='1','self comments do not notify self')
    actor.request('send_message.php',dict(receiver_id=uid,message='Private notification test body'),True)
    check(sql("SELECT COUNT(*) FROM notifications WHERE user_id="+uid+" AND kind='message'")=='1','message recipient notified')
    check('Private notification test body' not in owner.request('notifications.php')[1],'notification previews omit private message body')
    data=json.loads(owner.request('notification_count.php')[1]); check(data['unread']>=4,'unread badge includes received activity')
    nid=sql('SELECT MAX(id) FROM notifications WHERE user_id='+uid)
    check(actor.request('notifications.php',dict(action='read',id=nid))[0]==404,'cannot mark another user notification read')
    check(owner.request('notifications.php',dict(action='read',id=nid),token=False)[0]==403,'notification mutation requires CSRF')
    owner.request('notifications.php',dict(action='read',id=nid))
    check(sql('SELECT is_read FROM notifications WHERE id='+nid)=='1','mark individual notification read')
    actor_unread=sql('SELECT COUNT(*) FROM notifications WHERE user_id='+vid+' AND is_read=0')
    owner.request('notifications.php',dict(action='read_all'))
    check(json.loads(owner.request('notification_count.php')[1])['unread']==0,'mark all read clears own unread badge')
    check(sql('SELECT COUNT(*) FROM notifications WHERE user_id='+vid+' AND is_read=0')==actor_unread,'mark all does not affect others')
    fields=dict(action='create_staff',username='qa_employee',email='employee@example.test',bio='',password='Employee-password-123',staff_role='employee')
    fields['permissions[]']=['posts.view']
    check('Changes saved' in staff_action(fields)[1],'administrator creates employee with selected access')
    sid=sql("SELECT id FROM users WHERE email='employee@example.test'")
    employee=Client(); employee.request('login.php'); employee.request('login.php',dict(email='employee@example.test',password='Employee-password-123'))
    check(employee.request('admin.php?tab=posts')[0]==200,'employee can view granted section')
    check('Edit content' not in employee.request('admin.php?tab=posts')[1],'view-only employee sees no edit controls')
    for tab in ['users','messages','audit','team']:
        check(employee.request('admin.php?tab='+tab)[0]==403,'employee cannot open ungranted '+tab)
    check(employee.request('admin.php?tab=posts',dict(action='delete_post',id=pid))[0]==403,'view permission cannot mutate content')
    check(employee.request('admin.php',dict(action='create_staff',username='bad'))[0]==403,'employee cannot create staff through forged request')
    owner.request('add_post.php',dict(content='Staff notification scope'))
    check('new community post' in employee.request('notifications.php')[1],'staff notified only for granted section')
    check('new member' not in employee.request('notifications.php')[1],'ungranted member events stay private')
    fields.update(action='save_staff',id=sid,password=''); fields['permissions[]']=['posts.manage']
    staff_action(fields)
    check(employee.request('notification_count.php',ajax=True)[0]==401,'permission changes revoke previous staff session')
    employee.request('login.php'); employee.request('login.php',dict(email='employee@example.test',password='Employee-password-123'))
    check('Changes saved' in employee.request('admin.php?tab=posts',dict(action='save_post',id=pid,content='Employee reviewed this post'))[1],'employee can use granted manage permission')
    check('post was edited' in owner.request('notifications.php')[1],'content owner notified of moderation')
    fields['permissions[]']=[]; staff_action(fields)
    employee.request('login.php'); employee.request('login.php',dict(email='employee@example.test',password='Employee-password-123'))
    check(employee.request('admin.php?tab=posts')[0]==403,'revoked permission blocks previously available content')
    check('new community post' not in employee.request('notifications.php')[1],'revoked permission hides historical restricted notifications')
    manager=dict(action='create_staff',username='qa_manager',email='manager@example.test',bio='',password='Manager-password-123',staff_role='manager')
    manager['permissions[]']=['users.manage']
    staff_action(manager)
    mid=sql("SELECT id FROM users WHERE email='manager@example.test'")
    check('users.view' in sql('SELECT staff_permissions FROM users WHERE id='+mid),'manage permission includes view')
    check(sql('SELECT is_admin FROM users WHERE id='+mid)=='0','manager never receives administrator flag')
    manager['email']='badrole@example.test';manager['username']='badrole';manager['staff_role']='administrator'
    check('Choose manager or employee' in staff_action(manager)[1],'cannot create administrator through team form')
    check(actor.request('admin.php?tab=team')[0]==403,'ordinary member cannot access staff management')
    check(root.request('admin.php?tab=users',dict(action='delete_user',id=sid))[0]==200 and sql('SELECT COUNT(*) FROM users WHERE id='+sid)=='1','member management cannot target staff identities')
    # Keep small notification and staff fixtures for browser verification.
